---
  zh_CN:
    10200: "成功"
    10400: "错误"
    10401: "未授权:没有登录或登录过期"
    10403: "没有权限:服务器拒绝请求"
    10404: "未找到"
    10405: "方法禁用"
    10408: "请求超时"
    10412: "客户端请求信息的先决条件错误"
    10500: "服务器内部错误"
    10502: "错误网关:服务器作为网关或代理，从上游服务器收到无效响应"
    10503: "服务不可用"
    10504: "网关超时:服务器作为网关或代理，但是没有及时从上游服务器收到请求"
    40001: "账号不存在"
    40002: "密码错误"
    40003: "两次密码不一致"
    40004: "密码最小长度为：{}"
    40005: "密码最小长度为：{}，且必须包含字母和数字"
    40006: "实体不存在"
    40007: "不支持的登录方式"
    40008: "没有收到文件"
    41201: "没有获得此平台授权"
  en:
    10200: "Success"
    10400: "Error"
    10401: "Unauthorized: No login or expired login"
    10403: "No Permissions: Server rejects request"
    10404: "Not found"
    10405: "Method Disabled"
    10408: "Request Timed out"
    10412: "Client request for information prerequisite error"
    10500: "Server internal error"
    10502: "Error Gateway: Server acting as gateway or proxy receives invalid response from upstream server"
    10503: "Service Unavailable"
    10504: "Gateway Timeout: Server acting as gateway or proxy, but not receiving requests from upstream servers in time"
    40001: "Account number does not exist"
    40002: "Password error"
    40003: "Two inconsistent passwords"
    40004: "The minimum password length is:{}"
    40005: "The minimum length of the password is: {} and must contain letters and numbers"
    40006: "Entity does not exist"
    40007: "Login mode not supported"
    40008: "No file received"
    41201: "Not authorized for this platform"